server:
  port: 4854

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    oauth2.client:
      registration:
        google:
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_exp: ${JWT_ACCESS_EXP}
  refresh_exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
